### ISSUE TITLE
Recover ParsCit changes

### ISSUE THREAD

**Issue by crism** [pkp/xmlps#14]
The repository previously called for was `https://github.com/MichaelThessel/ParsCit.git`, no longer available. It appears that the version we’re using now, https://github.com/knmnyn/ParsCit.git, is missing some features that had been added. We need to find a checked-out copy of the MT fork, and recover those changes.

**Comment by axfelix** [comment]
Was able to restore an old server snapshot; /var/www/vendor/MichaelThessel/ParsCit is back for now. I'll diff it later so we can figure out what's up...

**Comment by axfelix** [comment]
Hmmm, the diff is extremely verbose. It's possible we had an old freeze of ParsCit -- I'll try diffing the known-working MichaelThessel version against a few older releases from their website later on. If memory serves I think that's more likely than us having made substantive changes.

**Comment by jalperin** [comment]
Have we tried reaching out to @MichaelThessel? Perhaps he has a copy, or
can at least tell us more about the changes.

**Comment by MichaelThessel** [comment]
Hi @axfelix, this was just a snapshot of a certain revision. No actual changes had been made to ParsCit. You should be able to figure out which revision by the checkout on the server. At the time there was a bug in the most recent version of ParsCit that broke the conversion. I don't recall the actual issue though. The issue might be resolved by now too.

**Comment by axfelix** [comment]
This should be taken care of: https://github.com/pkp/ParsCit

Right now I have both MichaelThessel/ParsCit and knmnyn/ParsCit in /vendor, both containing the old stable freeze we used. I'll discard one or the other after the conference once I double check which of the paths we're actually using at this point.

**Comment by axfelix** [comment]
Okay, we're good with just MichaelThessel/ParsCit in /vendor now and I've added the pkp repo as a remote there. Tested and working. Resolving this.
