### ISSUE TITLE
Find-as-you-type CSL selector on frontpage is slow and printing debug messages to log

### ISSUE THREAD

**Issue by axfelix** [pkp/xmlps#17]
Looks like several of these every time it's used:

2015/08/17 10:10:39	DEBUG	Error loading CSL style file. Libxml error:
Start tag expected, '<' not found

Worth looking into.

**Comment by crism** [comment]
I typically get this error when the citation style cache is not readable. For instance, after I run unit tests, the cache file is mode 600 owned by me, but then the web server, running as `www-data`, can’t read it. I added cache-clearing notes to the `README.md` on this.

**Comment by axfelix** [comment]
Hmmm -- not sure that's the issue here...

garnett@pkp-udev:/var/www/vendor/citation-style-language$ ls -la
total 72
drwxrwxr-x  3 www-data www-data  4096 Dec 17  2013 .
drwxrwxr-x 17 www-data www-data  4096 Aug 14 13:59 ..
drwxrwxr-x  5 www-data www-data 65536 Dec 17  2013 styles

**Comment by crism** [comment]
I saw it again; I think there is a race condition of some sort. I haven’t looked at it closely, but it seems like it returns a failure to load the cache, updates the cache, then runs, but the failure gets logged. Or something along those lines. That’s just a guess at this point…

**Comment by axfelix** [comment]
Race condition seems likely. That whole js block was already rewritten at least once; might not be particularly painful to do it again. But no hurry.

**Comment by crism** [comment]
The caching conflict causes this to manifest, because the cache has to be rebuilt, but the real problem, it appears, is that some of the CSL files have errors, which are causing the messages in the log.

**Comment by axfelix** [comment]
OK, so definitely need to add something that loops through, lints, and discards the busted ones after pulling from CSL repo. I should be able to get to that myself next week. Surprised that this would be happening, though; I assumed the CSL repo was pretty well maintained and that Zotero/Mendeley et al. pull from it directly.

**Comment by axfelix** [comment]
Verified that none of them have invalid XML, at least ...

**Comment by axfelix** [comment]
And just did a fresh clone of /vendor/citation-style-language/styles, since it seems like composer updates weren't getting new checkouts, based on the timestamps in the directory. So far I can't seem to duplicate the issue after having done that. Closing this for now.

**Comment by axfelix** [comment]
Crap, just hit this again. Reopening. Haven't touched the /styles directory since last comment, and it's 775 www-data:www-data.

**Comment by axfelix** [comment]
This is caused by /var/www/var/cache/zfcache-ea/zfcache-citationstyleconversionCitationstylesCitationstylelist.dat not being owned by the webserver user. Fixed.

**Comment by shaharyarahmad** [comment]
Still having the same issue, the same problem is happening again. I get the following error when trying to select citation styles.

Error loading CSL style file. Libxml error:
Start tag expected, '<' not found

**Comment by axfelix** [comment]
Hi @shaharyarahmad -- have you made sure that [xmlps-root]/var/cache/zfcache-ea/zfcache-citationstyleconversionCitationstylesCitationstylelist.dat is owned by the webserver user?

**Comment by shaharyarahmad** [comment]
This file doesn't seem to exist.

**Comment by axfelix** [comment]
Is the directory owned by the webserver user, at least?

**Comment by shaharyarahmad** [comment]
yes it is

**Comment by shaharyarahmad** [comment]
Updated permissions and owners for both zfcache-ae and /vendor/citation-style-language/styles, still no changes

**Comment by axfelix** [comment]
Are you running on an otherwise stock Ubuntu 14.04?

**Comment by shaharyarahmad** [comment]
yep, installed using xmlps-vagrant

**Comment by axfelix** [comment]
Ok -- and the processing queues (ps aux | grep php) are running as the www-data webserver user, not as your user?

**Comment by shaharyarahmad** [comment]
They're running as www-data

**Comment by shaharyarahmad** [comment]
this is the output
www-data  1123  1.1  0.8 215788 26200 ?        S    18:23   0:00 php public/index.php queue doctrine bibtex --start
www-data  1124  1.1  0.8 215532 26196 ?        S    18:23   0:00 php public/index.php queue doctrine bibtexreferences --start
www-data  1125  1.0  0.8 215788 26196 ?        S    18:23   0:00 php public/index.php queue doctrine cermine --start
www-data  1126  1.0  0.8 215788 26196 ?        S    18:23   0:00 php public/index.php queue doctrine citationstyle --start
www-data  1127  1.1  0.8 215788 26196 ?        S    18:23   0:00 php public/index.php queue doctrine docx --start
www-data  1131  1.1  0.8 215788 26200 ?        S    18:23   0:00 php public/index.php queue doctrine epub --start
www-data  1132  1.1  0.8 215788 26196 ?        S    18:23   0:00 php public/index.php queue doctrine html --start
www-data  1133  1.0  0.8 215788 26196 ?        S    18:23   0:00 php public/index.php queue doctrine merge --start
www-data  1134  1.1  0.8 215788 26196 ?        S    18:23   0:00 php public/index.php queue doctrine nlmxml --start
www-data  1135  1.1  0.8 215788 26196 ?        S    18:23   0:00 php public/index.php queue doctrine pathfinder --start
www-data  1136  1.2  0.8 215788 26196 ?        S    18:23   0:00 php public/index.php queue doctrine pdf --start
www-data  1137  1.0  0.8 215788 26192 ?        S    18:23   0:00 php public/index.php queue doctrine references --start
www-data  1138  1.1  0.8 215788 26196 ?        S    18:23   0:00 php public/index.php queue doctrine wppdf --start
www-data  1139  1.1  0.8 215788 26200 ?        S    18:23   0:00 php public/index.php queue doctrine xmp --start
www-data  1140  1.0  0.8 215788 26196 ?        S    18:23   0:00 php public/index.php queue doctrine zip --start
www-data  1141  1.2  0.8 215788 26200 ?        S    18:23   0:00 php public/index.php queue doctrine ner --start
www-data  1142  1.0  0.8 215788 26200 ?        S    18:23   0:00 php public/index.php queue doctrine parsCit --start
www-data  1143  1.0  0.8 215788 26200 ?        S    18:23   0:00 php public/index.php queue doctrine grobid --start
vagrant   1781  0.0  0.0  12832  1016 pts/1    R+   18:23   0:00 grep --color=auto php

**Comment by axfelix** [comment]
Hmmmm, OK. I'll have to spend some more time trying to duplicate this later in the week.

**Comment by shaharyarahmad** [comment]
No worries, appreciate your help.
