### ISSUE TITLE
Logs are too verbose

### ISSUE THREAD

**Issue by axfelix** [pkp/xmlps#18]
Right now we're getting the entirety of the XML and HTML outputs for a given article printed to the system logs, which will probably eat up the DB over time; need to look into fixing this.

**Comment by axfelix** [comment]
Q: @crism, do you think that fixing this would be as simple as chucking this last bit in this and similar modules? https://github.com/pkp/xmlps/blob/master/module/NlmxmlConversion/src/NlmxmlConversion/Model/Converter/Metypeset.php#L116

I notice there's something above that redirects STDERR to STDOUT, and we probably /would/ want to capture STDERR in the logs, so it might be easier to redirect STDERR to STDOUT and then redirect STDOUT to /dev/null instead (or would that also chuck STDERR if it's already on STDOUT?). Need to replicate this for a couple of other modules too, at least one of which probably has its actual output on STDOUT (as opposed to a filepath), so we need to be careful about that.

**Comment by axfelix** [comment]
Hm, this seemed not to do anything: https://github.com/pkp/xmlps/commit/bc97fef543446132e5b271ecd56f20fa0f4ade79

**Comment by crism** [comment]
@axfelix, I think `2>&1 1>/dev/null` is the incantation you’re looking for.

More precisely, though, I think we want to capture `STDERR` and `STDOUT`, but only log them if the process doesn’t succeed. This is part of the overall review I’m trying to start on.

**Comment by crism** [comment]
It’s also worth noting that we’re using a logger with different levels, and most of the complete log messages are at debug or info levels. Running production, we’d want to run at warning or error level.

**Comment by axfelix** [comment]
Setting log level to warn seems to have fixed verbosity issues for all but Pandoc and HTML conversion, which probably don't respect PHP log levels.
