### ISSUE TITLE
XML errors in CSL files

### ISSUE THREAD

**Issue by crism** [pkp/xmlps#23]
When first running the citation style module, the log fills up with XML parsing errors. It’s likely that some of the `.csl` files are malformed.

**Comment by axfelix** [comment]
Hm, thanks. This would explain some of the weirdness in the logs when using the autocomplete on the web frontend, too? Should be easy enough to loop over them with xmllint.

**Comment by crism** [comment]
Oops, this is actually redundant with #17.
