### ISSUE TITLE
Exceptions in queue processors are caught silently

### ISSUE THREAD

**Issue by crism** [pkp/xmlps#24]
While investigating #15, it seems that exceptions in a queue are caught, resulting in the job never finishing, rather than being set to failed status. From `MergeXMLOutputs\Model\Queue\Job\MergeJob.php`:
```php
        $meTypesetDocument = $job->getStageDocument(JOB_CONVERSION_STAGE_NLMXML);
        if (!$meTypesetDocument) {
            throw new \Exception('Couldn\'t find the meTypeset output');
        }
```

**Comment by crism** [comment]
Queues should set the job state to failure when their workers throw an exception. They should log the exception, as well. However, the queues don’t have a logger as it currently stands… is adding a logger to each queue too intrusive?

**Comment by axfelix** [comment]
No, but I'd love to abstract some of that out so there doesn't get to be so much code duplication in every module (similar to how there are currently way too many places where we need to manually name every module).

**Comment by crism** [comment]
The actual error message might could be clearer, but it needs to be a little generic since it’s coming from a superclass. Comments welcome.

**Comment by axfelix** [comment]
This is exactly what I had in mind, probably best to pull in @asmecher for some oversight here though -- background: each module has two components, a "worker" and the actual "converter," there wasn't proper logging on the "workers" until now so individual module failures weren't handled as intelligently as we liked, and rather than add duplicated code to every individual worker, we're now basically wrapping the worker calls in try/catch. Want to ensure this doesn't strike you as hugely Wrong on principle because it's what I'd do and that's usually alarm bells. Thanks @crism!

**Comment by crism** [comment]
Any comments, @asmecher? I think this is done, unless you have suggestions for improvements.

**Comment by asmecher** [comment]
I'm not sure I can add much specifically, as I'm not familiar with the codebase. As things stand, are errors logged somewhere useful?

**Comment by crism** [comment]
They are, @asmecher, but they’re generic. See ca074372daac910875c74ab0c87cb6d4c98c360f—the message is just “A worker threw an exception:” and the exception thrown. We *could*—with a fair bit of additional work—add more detail about which job, at which point, etc., or even make our own `Exception` subclass to use. I think this is good enough, but would like one other person to concur before I merge this upward. `(-:`

**Comment by asmecher** [comment]
Could the worker itself not log something more specific?

**Comment by crism** [comment]
Yes, but currently, lots of the workers throw exceptions, and the unit tests expect them. We’d have to rewrite every single one of them to log a message and set the state to failure, instead of throwing the exception.

Also, it actually seems like throwing an exception is the right thing to do, in the face of an unexpected situation (like missing input) for the workers—though I could be persuaded otherwise. We just need to catch it and handle it correctly, which we weren’t doing.

**Comment by asmecher** [comment]
Agreed, exceptions are a good thing to use here. I do think it's worth putting a little time into getting something useful in the log, rather than just "Aughhhh" -- but I'm still not sure why the worker exceptions (with exceptions) can't get passed up to the queue and managed there with something more specific?

**Comment by crism** [comment]
The exceptions to get passed to the queue—or rather, caught by the queue, which then logs the exception text. The prefix to the log message is generic. For example, if `DocxConversion\Model\Converter\Unoconv` can’t find its input, the queue would log:
```
A worker threw an exception:
Input file doesn't exist
```
In this case, you’d be left wondering *which* worker threw it, since the workers only log the start of their processes at debug or higher level. This could be addressed by improving the exception text in `Unoconv` (and elsewhere).

The reason for that is that we’re doing it in the queue superclass; to make the prefix specific to each queue, we’d have to edit it into each queue, which seemed unnecessary.

**Comment by asmecher** [comment]
Don't the queues have names, e.g. subclass names or something that should be accessible via introspection? [this is where I can only speculate vaguely]

**Comment by crism** [comment]
Ah, that’s a good idea. Lemme look more closely at what’s available there…

**Comment by crism** [comment]
I think that’ll do it. Sending a pull request.
