### ISSUE TITLE
Enable PDF input, using CERMINE entirely without meTypeset

### ISSUE THREAD

**Issue by axfelix** [pkp/xmlps#25]
Should be possible now to do a much simpler workflow if the uploaded filetype is PDF -- skipping LibreOffice and meTypeset steps entirely, go directly to CERMINE, skip Merge, and then use the CERMINE output XML for the rest of the stack (ParsCit, HTML/PDF/ePub renders, etc.).

**Comment by axfelix** [comment]
This obviously isn't going to be as much as a value-add as our full suite is geared toward doc input, but we still get a lot of people trying to upload PDFs.

**Comment by crism** [comment]
I think the right thing here is to add a new first stage which sets some flag(s), which later stages can consult. This would also be a hook on which to hang future decision-making tools like the proposed machine-learning pieces.

**Comment by crism** [comment]
Ugh… flags have to map to database columns (*e.g.* `Manager\Entity\Job::$referenceParsingSuccess`, which maps to `Job.referenceParsingSuccess` in the database). It would be too easy to have a proliferation of flags, leading to a proliferation of database columns and incessant migrations… but it would also be easy to have a single new enum that becomes an opaque and cryptic vector of multiple flags. Hrm.

**Comment by axfelix** [comment]
flags have to map to database columns?! Whose idea was that? :)

I'm going back and forth on this on my head but "single enum" might still be a wiser idea just based on the amount of work and cruft saved (one vector can only ever be so opaque and cryptic; multiple vectors can only ever be so straightforward).

Speaking as someone who'd, y'know, rather write an overlong shell script than ever touch Java.

**Comment by crism** [comment]
Currently planning a flag for input type. That should be orthogonal to other values, including conversion strategy.

**Comment by crism** [comment]
Seems to work; sent a pull request.
