### ISSUE TITLE
Troubles after install trying to Initialize the database

### ISSUE THREAD

**Issue by CeDe1** [pkp/xmlps#26]
I'm stuck at Initialize the database. I can't find this path:
# vendor/doctrine/doctrine-module/bin/doctrine-module orm:schema-tool:update --force
I'm quite new and I'm trying to figure out if i'm missing to install something like one of this:
https://github.com/doctrine/DoctrineOXMBundle
https://github.com/doctrine/DoctrineORMModule

Thanks in advance

**Comment by axfelix** [comment]
The composer self-update and composer install should take care of instantiating the vendor directory, including the doctrine paths ... are those the only things you're missing in /vendor after running composer?

**Comment by CeDe1** [comment]
Finally, after some rounds with it, after tried to install the composer I get an error with some info  about my php version compatibility with the latest composer so now I'm working on this. So this may be why I was getting an message about the "missing" path. Thanks for your quick answer

**Comment by axfelix** [comment]
No problem? Can we mark this as fixed?

**Comment by CeDe1** [comment]
Yes!

2015-10-02 13:49 GMT-03:00 axfelix <notifications@github.com>:

> No problem? Can we mark this as fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pkp/xmlps/issues/26#issuecomment-145084062>.
>



-- 





All beings tremble before violence

All fear death
All love life

See Yourself In Others

Then whom can you hurt?
What harm can you do?


Buddha
