### ISSUE TITLE
Move XML consumers to post-XML merge

### ISSUE THREAD

**Issue by crism** [pkp/xmlps#30]
The two XML branches (meTypeset→parsCit etc. and CERMINE) should be merged before any XML-consuming processes (epub, HTML, PDF) are fired.

**Comment by axfelix** [comment]
Yup!

**Comment by axfelix** [comment]
FYI, this seems to have worked (and the images are now in the ePub too!), but the resulting ePub may not be valid anymore ... only works in one of the two readers I tested. I'll try a third and decide if this needs to be looked at, and try to figure out what could be going wrong...

**Comment by axfelix** [comment]
See https://github.com/pkp/xmlps/issues/31. Fun one.
