### ISSUE TITLE
Using underscore characters as a separator in a document results in them being classified as a section title. 

### ISSUE THREAD

**Issue by jnicolls** [pkp/xmlps#36]
I.e the following: 

\___________________________

Will be classifed as:

\<sec\> 
      \<title\>____________________\</title\>

**Comment by axfelix** [comment]
Thanks, this is probably a pretty simple meTypeset pull. I'll look into it.

**Comment by axfelix** [comment]
Can I have an example document for this issue?

**Comment by axfelix** [comment]
@jnicolls Ping again -- was there an example doc for this issue?
