### ISSUE TITLE
Add more webserver configuration details to setup instructions

### ISSUE THREAD

**Issue by axfelix** [pkp/xmlps#37]
Just did a quick dogfood test and, when following our setup instructions to the letter, the only thing really lacking is apache config notes, as those might not be correct out of the box. This is largely a good thing and only needs minor adjustments.

**Comment by axfelix** [comment]
@kaschioudi, would you mind clarifying what you had to do to get the header graphic working on your instance? You've looked at it more recently than I have.

**Comment by kaschioudi** [comment]
It wasn't displaying when I setup a vagrant vm but it works in the cloud. so I'm not sure why.

**Comment by axfelix** [comment]
Fixed by all of my commits over the past week :)
