### ISSUE TITLE
audit how disk usage grows over time

### ISSUE THREAD

**Issue by axfelix** [pkp/xmlps#39]
Now that we're pushing large corpora through daily tests, we need to make sure we're purging old jobs appropriately. Might want to set a flag for some users so that their jobs are cleaned out more quickly?

**Comment by axfelix** [comment]
@crism, wouldn't mind your thoughts here when you're done with https://github.com/pkp/xmlps/issues/28

**Comment by crism** [comment]
I’d probably do this through `cron`—for select users (you, me, especially Joseph), any job more than a day old gets nuked.

**Comment by crism** [comment]
Maybe two days.

**Comment by axfelix** [comment]
Database and files? No reason to just do one and not the other, right?

**Comment by axfelix** [comment]
Apart from the relative unwisdom of putting an rm -rf (and the SQL password) in cron, this should do it, I think:

    cutoff=$(($(date +%s)-259200)); for x in $(mysql -uxmlps -p[password] -e "use xmlps; select id from job where userId = 275 and creationDate < $cutoff"); do rm -rf /var/www/var/documents/275/$x; mysql -uxmlps -p[password] -e "use xmlps; delete from job where userId = 275 and creationDate < $cutoff"; done

**Comment by asmecher** [comment]
Have a look at the `find` command's `-delete` and `-ctime` options; that's much safer than gluing into an `rm -rf`. If you're just deleting anything older than a certain number of days, that and a `DELETE FROM` should be all that's required, not a loop.

**Comment by crism** [comment]
@asmecher is right. @axfelix, where does the user ID come from there? You can use a dot-file (I forget which right now) for the MySQL credentials, rather than putting the password in the command.

**Comment by axfelix** [comment]
the user ID was just me grabbing the one associated with my own email address since that's the account we've been pushing most of the automated cron runs through as.

**Comment by crism** [comment]
@axfelix: Is the goal to purge only the old test jobs, or all old jobs? If it’s just the old jobs associated with specific user IDs, it’s a much easier goal…

**Comment by axfelix** [comment]
We can probably just set a longer differential from current epoch (that is preposterously fun to say) for old jobs originating from other users (like a few months?) and do it the same way.

Alec, I don't love the idea of using find -ctime rather than a loop created from MySQL results because then technically it's two different "queries" and there's a vague possibility we might wind up relating some files but not db entries (or vice versa) in a race condition. But I do appreciate wanting to get rid of the rm -rf.
