### ISSUE TITLE
JobControllerTest fails on cleanup

### ISSUE THREAD

**Issue by crism** [pkp/xmlps#4]
```
There was 1 error:

1) ApiTest\Controller\ApiControllerTest::testSubmitActionCannotBeAccessedLoggedOut
Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: An exception occurred while executing 'DELETE FROM user WHERE id = ?' with params [74]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`xmlps`.`job`, CONSTRAINT `FK_FBD8E0F864B64DCC` FOREIGN KEY (`userId`) REFERENCES `user` (`id`))
```

It looks like `createTestData()` makes a user and a job, but `cleanTestData()` then attempts to delete the user, but not the job linked to the user.

**Comment by crism** [comment]
Actually, the user is linked to by a job, which is in turn linked to by a document, so those three things must be deleted in that (reverse) order.

**Comment by crism** [comment]
Code review requested.

**Comment by asmecher** [comment]
@crism, I don't know this codebase, but at a glance this looks good. @axfelix, mind taking a peek?

**Comment by axfelix** [comment]
Looks good! I like the nested deletion like we discussed on slack, and emails are unique identifiers in the DB, so everything makes sense to me. Commenting certainly meets my standards too, though my commenting standards are very low :) Excellent first real commit. Thanks.

**Comment by crism** [comment]
I think that fixes it; merging into `dev/install-notes`, but we’re not out of the woods yet!
