### ISSUE TITLE
Unit tests rely on sendmail

### ISSUE THREAD

**Issue by crism** [pkp/xmlps#5]
The `testRegisterActionValidUser()` test attempts to use `sendmail` to send an actual e-mail to `unittestuser2@example.com`. This seems inappropriate, and also fails on a dev machine without sendmail installed.

**Comment by crism** [comment]
I think the right solution is to use `setCallable()` in `Zend\Mail\Transport\Sendmail` to use a testing stub instead.

**Comment by axfelix** [comment]
Any instance where "some bin that is hopefully on the path" is used in place of an actual PHP function is generally my fault, and changes are welcomed.

**Comment by axfelix** [comment]
Any activity on this?

**Comment by crism** [comment]
@axfelix—just turning my attention back to this now.
