### ISSUE TITLE
Recent Citation fixes seem to have broken Author name whitespace in HTML output

### ISSUE THREAD

**Issue by axfelix** [pkp/xmlps#59]
![screenshot from 2016-02-15 12 52 18](https://cloud.githubusercontent.com/assets/252047/13059990/05f5705a-d3e3-11e5-9f89-51231cfd1622.png)

**Comment by axfelix** [comment]
Should be able to reproduce in this document -- note that the names are coming out with slightly broken spacing in the XML, and this leads to even more broken spacing in the HTML. This might involve two different fixes, pertaining to some of the stuff I tried to do (and screwed up) in https://github.com/pkp/xmlps/issues/60

[eeg_comicsans.docx](https://github.com/pkp/xmlps/files/159291/eeg_comicsans.docx)

`<name><surname>Solomon</surname><given-names>GailE</given-names></name>`

**Comment by kaschioudi** [comment]
@axfelix ; which version of the codebase was used? the HTML output seems fine using latest code on master branch. 

![eeg_html_output](https://cloud.githubusercontent.com/assets/4896270/13581875/0c8dcdb4-e477-11e5-820a-5d110998ba2f.JPG)

**Comment by axfelix** [comment]
Huh! It's possible I fixed it in my last couple commits after all... but I reverted them on the live instance as I thought I'd broken bibtex output. Are you still getting .bib files as an available output format with that code?

**Comment by kaschioudi** [comment]
Yes, there is a document.bib file.

**Comment by axfelix** [comment]
Ha! I guess those commits worked after all. Thanks for testing, I'll fast forward the live instance back to head. Guess we can close this!

**Comment by axfelix** [comment]
This seems to still be an issue -- example in http://pkp-udev.lib.sfu.ca/manager/details/id/19284

**Comment by axfelix** [comment]
Closing again. Was a dependency issue on our demo site.
