### ISSUE TITLE
UnoconvTest fails

### ISSUE THREAD

**Issue by crism** [pkp/xmlps#6]
```
1) DocxConversionTest\Model\Converter\UnoconvTest::testConversion
Failed asserting that true matches expected false.

/home/crism/src/xmlps/module/DocxConversion/test/DocxConversionTest/Model/Converter/UnoconvTest.php:53
```

**Comment by crism** [comment]
Why are we hardcoding `/opt/libreoffice4.2/program/python` to call `unoconv`? That seems… odd.

**Comment by axfelix** [comment]
Fear of regressions in LibreOffice's conversion engine around the time of the 4.3 release, afaik.

**Comment by axfelix** [comment]
Also, the LibreOffice stack is crazy enough that a number of distros do just stick it in opt rather than try to unpack it to usr/share. But I agree this could probably change.

**Comment by crism** [comment]
When unoconv is installed via apt, the installed executable works. Not sure what, if anything, to actually check in on this issue… just documentation, I think.
