### ISSUE TITLE
<citation> elements in ref-list should actually be labeled <element-citation>

### ISSUE THREAD

**Issue by axfelix** [pkp/xmlps#60]
Minor validation fix just noticed by development partner.

**Comment by axfelix** [comment]
Also, `<ref rid>` should've been `<ref id>`. Just fixed both of these in https://github.com/pkp/xmlps/commit/6340ed5f77b57f76e6286990eb83f68f300b4c62

**Comment by axfelix** [comment]
Changing that XSL is resulting in lots of and seeming to fail all documents with citations, with this in the logs:

2016/02/22 14:43:51
DEBUG	Error loading the XSL style sheet

No idea how that's caused a breakage, it's such a small commit and there aren't any permissions issues, unless the stack had somehow cached the old XSLT for the in-progress jobs when I restarted the queues. Reverted to the prior commit for now.

**Comment by axfelix** [comment]
Oh, dammit, I forgot to change the closing tag of `<element-citation>`.

I really shouldn't multitask.

**Comment by axfelix** [comment]
Looks like the Pandoc merge is still broken.

**Comment by axfelix** [comment]
Reverted on the demo instance for now, will get back to this later. Thought I caught the other needed fixes but perhaps not: https://github.com/pkp/xmlps/commit/a9d49954614dc6a63ef5418ae098e84e7aa2c795

**Comment by axfelix** [comment]
@kaschioudi can you verify this is working on a checkout of master too? Hopefully it's all fixed now; I must have been confused when testing.

**Comment by kaschioudi** [comment]
from what I see, your fixes are working correctly :)

**Comment by axfelix** [comment]
Thanks! Sorry for the confusion here. Closing.
