### ISSUE TITLE
Converter/ReferencesTest fails

### ISSUE THREAD

**Issue by crism** [pkp/xmlps#7]
```
1) ReferencesConversionTest\Model\Converter\ReferencesTest::testConversion
Failed asserting that false is true.

/home/crism/src/xmlps/module/ReferencesConversion/test/ReferencesConversionTest/Model/Converter/ReferencesTest.php:58
```

**Comment by crism** [comment]
The line in question:
```php
        $this->assertTrue(is_file($this->testOutputFile));
```
Which means something is going wrong up above:
```php
        $this->references->setOutputFile($this->testOutputFile);
        $this->references->convert();
```

**Comment by crism** [comment]
`ReferencesConversion\Model\Converter::convert()` fails parsing the bibliography.

**Comment by crism** [comment]
`ReferencesConversion\Model\Converter::parsCitExecute()` has a hard-coded reference to `vendor/MichaelThessel` which is no longer valid.

**Comment by crism** [comment]
The `knmnyn` version of ParsCit has Perl module dependencies. Yay! More to document…

**Comment by crism** [comment]
RTFM, @crism. This is covered by the ParsCit requirements, as noted in our `README`.

**Comment by crism** [comment]
Got my local set-up working—had to do a tiny bit of C++ hacking to get CRF++ to build, but sorted!

**Comment by axfelix** [comment]
Glad! I think there's still a note submitted from me a few years ago on the Parscit project page FAQ about getting the crf libs working :)
