### ISSUE TITLE
XSLTProcessor is an undocumented dependency

### ISSUE THREAD

**Issue by crism** [pkp/xmlps#8]
Required by `Bibtexreferences`. Probably fixable in Composer.

**Comment by crism** [comment]
Er… no, it’s a PHP built-in. So why:
```
.................................................PHP Fatal error:  Class 'XSLTProcessor' not found in /home/crism/src/xmlps/module/BibtexreferencesConversion/src/BibtexreferencesConversion/Model/Converter/Bibtexreferences.php on line 172
```
Hmm.

**Comment by axfelix** [comment]
PHP version? I think native XSLT handling is recent-/ish/ but I'd be surprised if that were the issue. Bootstrapping? I'm really bad at PHP bootstrapping.

**Comment by crism** [comment]
http://www.php.net/manual/en/xsl.installation.php

Adding note to `README.md`.
