### ISSUE TITLE
PandocTest fails

### ISSUE THREAD

**Issue by crism** [pkp/xmlps#9]
```
1) CitationstyleConversionTest\Model\Converter\PandocTest::testConversion
Failed asserting that false is true.

/home/crism/src/xmlps/module/CitationstyleConversion/test/CitationstyleConcersion/Model/Converter/PandocTest.php:90
```

**Comment by crism** [comment]
… concersion‽

**Comment by axfelix** [comment]
Citation style coersion. That's a better name for fuzzy parsing :)

**Comment by crism** [comment]
This was due to my not having `pandoc-citeproc`, a distinct package in apt from `pandoc`.

**Comment by axfelix** [comment]
Good to know. I think that's probably changed in Ubuntu sources since when we set this up, but anytime something is handled by the package manager at least somewhat gratefully I'm happy.
